<fieldset class="product-options" id="product-options-wrapper">
    <?php echo $this->getChildHtml('', true, true);?>
    <span style="display:none;" class="scp-please-wait"><img src="<?php echo $this->getSkinUrl('images/scp/scp-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading...') ?> &nbsp;</span>
    <?php // add placeholder div for any ajax-loaded custom options ?>
    <div id="SCPcustomOptionsDiv"></div>
    <?php if ($this->hasRequiredOptions()):?>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <?php endif;?>
</fieldset>

<script type="text/javascript">
    $$('#product-options-wrapper dl').each(function(label) {
        label.addClassName('last');
    });
    jQuery(document).ready(function(){
	    var inputs = jQuery("#product_addtocart_form").on("change input", function(e){
		    var oriinsertAdvice = Validation.insertAdvice;
	    	Object.extend(Validation, {
	    		insertAdvice : function(nelm, nadvice){
	    			jQuery("#choice_qty_price").before(nadvice);
	    		}		
	    	});
		    
	    	if(spConfig.getMatchingSimpleProduct() && productAddToCartForm.validator.validate()){
	   		    var prices = applySizePrice();
	   		    updateTotalPrice(prices);
	    		jQuery("#choice_qty_price").show();
	    		jQuery("#selected_product .ajaxcontent").html("Some product details to be fetched from server");
	    	}
	    	else{
		    	jQuery("#choice_qty_price").hide();
	    	}

	    	Object.extend(Validation, {
	    		insertAdvice : oriinsertAdvice
	    	});
	    });
    });
</script>
