<fieldset class="product-options" id="product-options-wrapper">
    <?php echo $this->getChildHtml('', true, true);?>
    <span style="display:none;" class="scp-please-wait"><img src="<?php echo $this->getSkinUrl('images/scp/scp-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading...') ?> &nbsp;</span>
    <?php // add placeholder div for any ajax-loaded custom options ?>
    <div id="SCPcustomOptionsDiv"></div>
    <?php if ($this->hasRequiredOptions()):?>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <?php endif;?>
</fieldset>

<script type="text/javascript">
	var nextbtn = jQuery('<a href="#" class="button nextbutton">Volgende</a>');
	nextbtn.click(nextoption);

    Object.extend(Validation, {
	    isVisible : function(elm) {
	        while(elm.tagName != 'BODY') {
	            if(!$(elm).visible()){
		            var jelm = jQuery(elm);
		            if(jelm.hasClass("super-attribute-select")){
			            var next = jelm.next();
			            if(next.hasClass('validation-advice')){
				            next = next.next();
			            }
			            if(next.is(':visible') && next.hasClass('image_picker_selector')){
				            return true;
			            }
		            }
	            	return false;
	            }
	            elm = elm.parentNode;
	        }
	        return true;
	    },
    });

	function setDtVal(selector, val){
		var ele = jQuery(selector);
		var curvalele = ele.find(".curval");
		if(curvalele.length == 0){
			ele.append('<span class="curval">'+ (val !== undefined ? val: "") + '</span>');
		}
		else{
			curvalele.html(val !== undefined ? val: "");
		}
	}
    
	jQuery("select.super-attribute-select, select.product-custom-option").bind("change", function(){
		nextoption();
		setDtVal(jQuery(this).parents("dd").prev(), jQuery(this).find("option:selected").text());
	});

    var dds = jQuery(".product-options dd");
    var dts = jQuery(".product-options dt");
    dds.hide();
    dts.addClass("collapsed");
    jQuery(dts[0]).removeClass("collapsed");
    jQuery(dds[0]).append(nextbtn)
    jQuery(dds[0]).show();

    function scpWewewoPriceReload(){
		    var prices = opConfig.reloadPrice();
   		 	if(typeof(productDesignGetExtraPrice) != 'undefined'){
	   		    var pdp = productDesignGetExtraPrice();
	   		    if(pdp > 0){
		   		    for(var i = 0 ; i < prices.length; i++){
			   		    prices[i].incl += pdp * prices[i].incl / prices[i].excl;
			   		    prices[i].price += pdp * prices[i].price / prices[i].excl;
			   		    prices[i].excl += pdp;
		   		    }
	   		    }
   		 	}
   		    if(typeof(applySizePrice) != 'undefined'){
	   			prices = applySizePrice(prices);
   		    }
			jQuery('.price-box').find(".regular-price .price").html(optionsPrice.formatPrice(prices[0].price));
			jQuery('.price-box').find(".price-including-tax .price").html(optionsPrice.formatPrice(prices[0].incl));
			jQuery('.price-box').find(".price-excluding-tax .price").html(optionsPrice.formatPrice(prices[0].excl));
   		    for(var i = 1 ; i < prices.length; i++){
	   		    if(prices[i].excl != prices[0].excl){
	   				jQuery('.price-box').find(".old-price .price").html(optionsPrice.formatPrice(prices[i].excl));
	   		    }
   		    }
   		    updateTotalPrice(prices);
    }

    function _reconfigureoption(){
		var dds = jQuery(".product-options dd");
	    var dts = jQuery(".product-options dt");
        dts.addClass("collapsed");
	    dds.hide();
	    var dt = jQuery(this);
	    dt.removeClass("collapsed");
	    var dd = dt.next();
	    dd.show();
	    dd.append(nextbtn);
	    var i = 0;
	    for(;i < dts.length; i++){
		    if(dts[i] == dt[0]){
			    break;
		    }
	    }
    	
	    for(;i < dts.length; i++){
	    	jQuery(dts[i]).unbind("click", _reconfigureoption);
    		jQuery(dts[i]).removeClass("clickable");
	    }
		nextbtn.show();
    	jQuery("#choice_qty_price").hide();
	}

    function nextoption(){
    	if(productAddToCartForm.validator.validate()){

    	    var dds = jQuery(".product-options dd");
    	    var dts = jQuery(".product-options dt");
    	    var i = 0;
    	    for(;i < dds.length; i++){
        	    if(jQuery(dds[i]).is(":visible")){
            	    var jddsip1 = jQuery(dds[i+1]);
            	    jddsip1.show();
            	    jddsip1.append(nextbtn);
        	        jQuery(dts[i+1]).removeClass("collapsed");
        	        
        	        jQuery(dts[i]).addClass("collapsed");
        	    	jQuery(dds[i]).hide();
        	    	for(var j = 0; j <= i; j++){ 
        	    		jQuery(dts[j]).click(_reconfigureoption);
        	    		jQuery(dts[j]).addClass("clickable");
        	    	}
        	    	
            	    break;
        	    }
    	    }

        	if(i == dds.length-1){
        		nextbtn.hide();
        		var sphtml = "<ul>";
        		for(var i = 0; i <= dts.length; i++){
            		var dti = jQuery(dts[i]);
            		var label = dti.find("label").html();
            		if(label !== undefined){
                		label = label.replace(/<em.*>\*<\/em>/i, "");
            			sphtml += "<li><label>"+label+"</label> <span class=\"curval\">"+dti.find(".curval").html()+"</span></li>";
            		}
        		}
        		sphtml += "</ul>";
        		jQuery("#selected_product .dynamic-content").html(sphtml);
    	    	jQuery("#choice_qty_price").show();
        	}
    	}
    	return false;
    }
    
    jQuery(document).ready(function(){
	    jQuery("#product_addtocart_form").on("change", scpWewewoPriceReload);
    });
</script>
