<?php
//SCP: This is part of the Custom Option AJAX response - it shows custom options for 'associated' products.

//opConfig is forced into global scope even if pulled in via ajax (by using window.)
//and also ensure correct form encoding
/* @var $this ShirtWorld_ShirtDesigner_Block_Catalog_Product_View_Options */

$product = $this->getProduct();

$_finalPrice = $product->getFinalPrice();
if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) {
	$_priceInclTax = Mage::helper('tax')->getPrice($product, $_finalPrice, true,
			null, null, null, null, null, false);
	$_priceExclTax = Mage::helper('tax')->getPrice($product, $_finalPrice, false,
			null, null, null, null, null, false);
} else {
	$_priceInclTax = Mage::helper('tax')->getPrice($product, $_finalPrice, true);
	$_priceExclTax = Mage::helper('tax')->getPrice($product, $_finalPrice);
}

$_tierPricesQty = array();
$_tierPrices = array();
$_tierPricesInclTax = array();
foreach ($product->getTierPrice() as $tierPrice) {
	$_tierPrices[] = Mage::helper('core')->currency(
			Mage::helper('tax')->getPrice($product, (float)$tierPrice['website_price'], false) - $_priceExclTax
			, false, false);
	$_tierPricesInclTax[] = Mage::helper('core')->currency(
			Mage::helper('tax')->getPrice($product, (float)$tierPrice['website_price'], true) - $_priceInclTax
			, false, false);
	$_tierPricesQty[] = $tierPrice['price_qty'];
}

?>
<script type="text/javascript">
    //<![CDATA[
    try{
        window.opConfig = new Product.Options(<?php echo $this->getJsonConfig() ?>);
        scpWewewoPriceReload();
        
        optionsPrice.tierPrices = <?php echo json_encode($_tierPrices); ?>;
        optionsPrice.tierPricesInclTax = <?php echo json_encode($_tierPricesInclTax); ?>;
        optionsPrice.tierPricesQty = <?php echo json_encode($_tierPricesQty); ?>;
	}catch(e){}
    
    $('product_addtocart_form').encoding = 'multipart/form-data';
    //]]>
</script>
<?php if (count($this->getOptions())): ?>
<dl>
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()) ?>
<?php foreach($_options as $_option): ?>
    <?php echo $this->getOptionHtml($_option) ?>
<?php endforeach; ?>
</dl>

<script type="text/javascript">
    $$('#product-options-wrapper dl').each(function(label) {
        label.removeClassName('last');
    });
    $$('#SCPcustomOptionsDiv dl').each(function(label) {
        label.addClassName('last');
    });
</script>
<?php endif; ?>
